# Generated by Django 5.0.3 on 2024-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Draft"), (2, "Published"), (3, "Archived")], default=1
            ),
        ),
    ]
