# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
    -   id: black
        name: black (python)
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        name: flake8 (python)
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        name: bandit (python)
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
-   repo: local
    hooks:
    -    id: migrations
         name: Check forgotten migrations (django)
         entry: python manage.py makemigrations --check
         language: system
         types: [python]
         pass_filenames: false
    -    id: migrations
         name: Check outdated po files (django)
         entry: python manage.py makemigrations --check
         language: system
         types: [python]
         pass_filenames: false
