[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
line_length = 88
py_version=310
profile = "black"
src_paths = ["test_project"]

# https://bandit.readthedocs.io/en/latest/config.html
[tool.bandit]
exclude_dirs = ["tests"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "test_project.settings.dev"
python_files = ["test_*.py"]
addopts = "--reuse-db"
